// Code generated by protoc-gen-go-validate. DO NOT EDIT.

package example

import (
	context "context"
	validator "github.com/aesoper101/protoc-gen-govalidate/validator"
)

var (
	_example2Rule = map[string]string{
		"A":      "required",
		"B":      "required",
		"Status": "oneof=0 1",
	}
	_example2NestedRule = map[string]string{
		"D": "required",
		"E": "required,gt=10",
	}
)

func init() {
	validator.Validator().RegisterStructValidationMapRules(_example2Rule, Example2{})
	validator.Validator().RegisterStructValidationMapRules(_example2NestedRule, Example2_Nested{})
}

func (x *Example2) Validate() error {
	return validator.Validator().Struct(x)
}

func (x *Example2) StructCtx(ctx context.Context) error {
	return validator.Validator().StructCtx(ctx, x)
}

func (x *Example2_Nested) Validate() error {
	return validator.Validator().Struct(x)
}

func (x *Example2_Nested) StructCtx(ctx context.Context) error {
	return validator.Validator().StructCtx(ctx, x)
}
