// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: examples/example.proto

package example

import (
	_ "github.com/aesoper101/protoc-gen-govalidate/govalidate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Example struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A string          `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B *Example_Nested `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *Example) Reset() {
	*x = Example{}
	if protoimpl.UnsafeEnabled {
		mi := &file_examples_example_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Example) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Example) ProtoMessage() {}

func (x *Example) ProtoReflect() protoreflect.Message {
	mi := &file_examples_example_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Example.ProtoReflect.Descriptor instead.
func (*Example) Descriptor() ([]byte, []int) {
	return file_examples_example_proto_rawDescGZIP(), []int{0}
}

func (x *Example) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

func (x *Example) GetB() *Example_Nested {
	if x != nil {
		return x.B
	}
	return nil
}

type Example_Nested struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	B string `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *Example_Nested) Reset() {
	*x = Example_Nested{}
	if protoimpl.UnsafeEnabled {
		mi := &file_examples_example_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Example_Nested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Example_Nested) ProtoMessage() {}

func (x *Example_Nested) ProtoReflect() protoreflect.Message {
	mi := &file_examples_example_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Example_Nested.ProtoReflect.Descriptor instead.
func (*Example_Nested) Descriptor() ([]byte, []int) {
	return file_examples_example_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Example_Nested) GetB() string {
	if x != nil {
		return x.B
	}
	return ""
}

var File_examples_example_proto protoreflect.FileDescriptor

var file_examples_example_proto_rawDesc = []byte{
	0x0a, 0x16, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x1a, 0x19, 0x67, 0x6f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x85, 0x01, 0x0a,
	0x07, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x0c, 0x8a, 0xea, 0x30, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x64, 0x52, 0x01, 0x61, 0x12, 0x38, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x2e, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x42, 0x11, 0x8a, 0xea, 0x30, 0x0d, 0x72, 0x65,
	0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x2c, 0x67, 0x74, 0x3d, 0x30, 0x52, 0x01, 0x62, 0x1a, 0x24,
	0x0a, 0x06, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x01, 0x62, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x0c, 0x8a, 0xea, 0x30, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x64, 0x52, 0x01, 0x62, 0x42, 0x75, 0x0a, 0x1d, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x61, 0x65, 0x73, 0x6f, 0x70, 0x65, 0x72, 0x31, 0x30, 0x31, 0x2e, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x50, 0x01, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x65, 0x73, 0x6f, 0x70, 0x65, 0x72, 0x31, 0x30, 0x31, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x67, 0x6f, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x3b, 0x65, 0x78, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0xa2, 0x02, 0x14, 0x41, 0x65, 0x73, 0x6f, 0x70, 0x65, 0x72, 0x31, 0x30,
	0x31, 0x47, 0x6f, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_examples_example_proto_rawDescOnce sync.Once
	file_examples_example_proto_rawDescData = file_examples_example_proto_rawDesc
)

func file_examples_example_proto_rawDescGZIP() []byte {
	file_examples_example_proto_rawDescOnce.Do(func() {
		file_examples_example_proto_rawDescData = protoimpl.X.CompressGZIP(file_examples_example_proto_rawDescData)
	})
	return file_examples_example_proto_rawDescData
}

var file_examples_example_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_examples_example_proto_goTypes = []interface{}{
	(*Example)(nil),        // 0: example.Example
	(*Example_Nested)(nil), // 1: example.Example.Nested
}
var file_examples_example_proto_depIdxs = []int32{
	1, // 0: example.Example.b:type_name -> example.Example.Nested
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_examples_example_proto_init() }
func file_examples_example_proto_init() {
	if File_examples_example_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_examples_example_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Example); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_examples_example_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Example_Nested); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_examples_example_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_example_proto_goTypes,
		DependencyIndexes: file_examples_example_proto_depIdxs,
		MessageInfos:      file_examples_example_proto_msgTypes,
	}.Build()
	File_examples_example_proto = out.File
	file_examples_example_proto_rawDesc = nil
	file_examples_example_proto_goTypes = nil
	file_examples_example_proto_depIdxs = nil
}
